# Site settings
author: George Blackmore
title: My Blog
header-img: img/home-bg.png
email: gtblackmore@gmail.com
copyright_name: George Blackmore
description: > # this means to ignore newlines until "baseurl:"
  This is my blog.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  gtblackmore

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
